"""New database schema

Revision ID: 03a5ffec4e8f
Revises: 
Create Date: 2025-10-01 03:55:19.721843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a5ffec4e8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount_deducted', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('outstanding_difference', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('full_payment', sa.Boolean(), nullable=False),
    sa.Column('no_payment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_records_grade'), 'employee_records', ['grade'], unique=False)
    op.create_index(op.f('ix_employee_records_name'), 'employee_records', ['name'], unique=False)
    op.create_index(op.f('ix_employee_records_unit'), 'employee_records', ['unit'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_number', sa.String(length=7), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_number'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_employee_records_unit'), table_name='employee_records')
    op.drop_index(op.f('ix_employee_records_name'), table_name='employee_records')
    op.drop_index(op.f('ix_employee_records_grade'), table_name='employee_records')
    op.drop_table('employee_records')
    # ### end Alembic commands ###
